name: Deploy to GCP App Engine

# Trigger the workflow on a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository's code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }} # Project ID set as a secret
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Service Account JSON key set as a secret

    #
